moviesDescription page added
hangingPandaReact/Ashish_movie pull request #3
Opened 2022-03-16 16:33 UTC by ashishprodev

2022-03-16 20:28 UTC, hangingPandaReact requested changes

2022-03-16 20:28 UTC, hangingPandaReact commented on src/screen/MoviesDescription.js
> +    <SafeAreaView style={{blackground: colors.black}}>
inline css has been used remove it

2022-03-16 20:28 UTC, hangingPandaReact commented on src/screen/MoviesDescription.js
> +        source={{
Covert these thing into component

2022-03-16 20:28 UTC, hangingPandaReact commented on src/screen/MoviesDescription.js
> +            <Text style={styles.Country}>India</Text>
these text should be a component and things should be used only component

2022-03-17 10:27 UTC, ashishprodev commented on App.js
> +      {/* <NavigationContainer>
okay sir

2022-03-17 10:28 UTC, ashishprodev commented on src/component/card/Card.js
> +          <Text style={styles.moviesName}>{item.Title}</Text>
okay sir, i will change

2022-03-17 10:29 UTC, ashishprodev commented on src/screen/MoviesDescription.js
> +            <Text style={styles.Country}>India</Text>
okay sir, i will wrap into details container

2022-03-17 10:29 UTC, ashishprodev commented on src/screen/MoviesDescription.js
> +        source={{
okay sir

2022-03-17 10:30 UTC, ashishprodev commented on src/screen/MoviesDescription.js
> +    <SafeAreaView style={{blackground: colors.black}}>
got it sir, i will change

2022-03-22 04:54 UTC, merged